# Generated by Django 4.1.5 on 2023-01-27 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.FloatField(max_length=10, null=True),
        ),
    ]
